#ddr pin xdc
create_clock -period 10.000 -name sysclk_i -add [get_ports sysclk]
set_property PACKAGE_PIN AD12 [get_ports sysclk]
set_property IOSTANDARD SSTL135 [get_ports sysclk]

set_property PACKAGE_PIN U29 [get_ports pcie_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_rst_n]

# PCI Express reference clock 100MHz
create_clock -period 10.000 -name pcie_sys_clk -waveform {0.000 5.000} [get_ports {pcie_ref_clk_p[0]}]
set_property PACKAGE_PIN G8 [get_ports {pcie_ref_clk_p[0]}]
# MGT locations

set_property LOC GTXE2_CHANNEL_X0Y11 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN F6 [get_ports {pcie_mgt_rxp[0]}]
set_property PACKAGE_PIN F2 [get_ports {pcie_mgt_txp[0]}]
set_property LOC GTXE2_CHANNEL_X0Y10 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN G4 [get_ports {pcie_mgt_rxp[1]}]
set_property PACKAGE_PIN H2 [get_ports {pcie_mgt_txp[1]}]
set_property LOC GTXE2_CHANNEL_X0Y9 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN H6 [get_ports {pcie_mgt_rxp[2]}]
set_property PACKAGE_PIN J4 [get_ports {pcie_mgt_txp[2]}]
set_property LOC GTXE2_CHANNEL_X0Y8 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN K6 [get_ports {pcie_mgt_rxp[3]}]
set_property PACKAGE_PIN K2 [get_ports {pcie_mgt_txp[3]}]
set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN M6 [get_ports {pcie_mgt_rxp[4]}]
set_property PACKAGE_PIN L4 [get_ports {pcie_mgt_txp[4]}]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN P6 [get_ports {pcie_mgt_rxp[5]}]
set_property PACKAGE_PIN M2 [get_ports {pcie_mgt_txp[5]}]
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN R4 [get_ports {pcie_mgt_rxp[6]}]
set_property PACKAGE_PIN N4 [get_ports {pcie_mgt_txp[6]}]
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells {pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN T6 [get_ports {pcie_mgt_rxp[7]}]
set_property PACKAGE_PIN P2 [get_ports {pcie_mgt_txp[7]}]

#gt

# 156.25MHz GT Reference clock constraint
create_clock -period 6.400 -name GT_REFCLK1 [get_ports gt_refclk1_p]
# Reference clock location
set_property PACKAGE_PIN E8 [get_ports gt_refclk1_p]
#set_property PACKAGE_PIN E7 [get_ports gt_refclk1_n]

#abcd
set_property PACKAGE_PIN E4 [get_ports {rxp[0]}]
set_property PACKAGE_PIN D2 [get_ports {txp[0]}]
set_property PACKAGE_PIN D6 [get_ports {rxp[1]}]
set_property PACKAGE_PIN C4 [get_ports {txp[1]}]
#set_property PACKAGE_PIN B6 [get_ports {rxp[2]}]
#set_property PACKAGE_PIN B2 [get_ports {txp[2]}]
#set_property PACKAGE_PIN A8 [get_ports {rxp[3]}]
#set_property PACKAGE_PIN A4 [get_ports {txp[3]}]


set_property PACKAGE_PIN B23 [get_ports sfpa_tx_dis]
set_property PACKAGE_PIN AA25 [get_ports sfpb_tx_dis]
set_property PACKAGE_PIN AD28 [get_ports sfpc_tx_dis]
set_property PACKAGE_PIN AB29 [get_ports sfpd_tx_dis]

set_property PACKAGE_PIN A23 [get_ports sfpa_rs0]
set_property PACKAGE_PIN AB25 [get_ports sfpb_rs0]
set_property PACKAGE_PIN Y30 [get_ports sfpc_rs0]
set_property PACKAGE_PIN AB30 [get_ports sfpd_rs0]

set_property PACKAGE_PIN A25 [get_ports sfpa_rs1]
set_property PACKAGE_PIN AD27 [get_ports sfpb_rs1]
set_property PACKAGE_PIN AA30 [get_ports sfpc_rs1]
set_property PACKAGE_PIN AC29 [get_ports sfpd_rs1]

set_property IOSTANDARD LVCMOS33 [get_ports sfpa_tx_dis]
set_property IOSTANDARD LVCMOS18 [get_ports sfpb_tx_dis]
set_property IOSTANDARD LVCMOS18 [get_ports sfpc_tx_dis]
set_property IOSTANDARD LVCMOS18 [get_ports sfpd_tx_dis]
set_property IOSTANDARD LVCMOS33 [get_ports sfpa_rs0]
set_property IOSTANDARD LVCMOS18 [get_ports sfpb_rs0]
set_property IOSTANDARD LVCMOS18 [get_ports sfpc_rs0]
set_property IOSTANDARD LVCMOS18 [get_ports sfpd_rs0]
set_property IOSTANDARD LVCMOS33 [get_ports sfpa_rs1]
set_property IOSTANDARD LVCMOS18 [get_ports sfpb_rs1]
set_property IOSTANDARD LVCMOS18 [get_ports sfpc_rs1]
set_property IOSTANDARD LVCMOS18 [get_ports sfpd_rs1]

#power con
#set_property PACKAGE_PIN AB18 [get_ports {power_con[0]}]
#set_property PACKAGE_PIN AB19 [get_ports {power_con[1]}]
#set_property PACKAGE_PIN AC19 [get_ports {power_con[2]}]
#set_property PACKAGE_PIN AB17 [get_ports {power_con[3]}]
#set_property PACKAGE_PIN AC17 [get_ports {power_con[4]}]
#set_property PACKAGE_PIN AE15 [get_ports {power_con[5]}]
#set_property PACKAGE_PIN AE14 [get_ports {power_con[6]}]
#set_property PACKAGE_PIN AA15 [get_ports {power_con[7]}]
#set_property PACKAGE_PIN AB15 [get_ports {power_con[8]}]
#set_property PACKAGE_PIN AC16 [get_ports {power_con[9]}]
#set_property PACKAGE_PIN AC15 [get_ports {power_con[10]}]
#set_property PACKAGE_PIN AC14 [get_ports {power_con[11]}]
#set_property PACKAGE_PIN AD14 [get_ports {power_con[12]}]
#set_property PACKAGE_PIN AA17 [get_ports {power_con[13]}]
#set_property PACKAGE_PIN AA16 [get_ports {power_con[14]}]
#set_property PACKAGE_PIN Y16 [get_ports {power_con[15]}]
##set_property PACKAGE_PIN W19  [get_ports LED]
##set_property PACKAGE_PIN F21  [get_ports d2_clk]

#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {power_con[15]}]


#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets west0_pin_out_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets west1_pin_out_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets west2_pin_out_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets west3_pin_out_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets west4_pin_out_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets west5_pin_out_IBUF[0]]

set_property DCI_CASCADE {34} [get_iobanks 33]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]


set_false_path -from [get_clocks -of_objects [get_pins pcie_system_i/mig_7series_0/u_pcie_system_mig_7series_0_2_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins pcie_system_i/xdma_0/inst/pcie_system_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins pcie_system_i/mig_7series_0/u_pcie_system_mig_7series_0_2_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets gdma_clk]
